version: "3.9"

services:
  eas-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresPassword
      POSTGRES_DB: eas-index
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  eas-indexer:
    build: .
    environment:
      CHAIN_ID: ${CHAIN_ID} 
      DATABASE_URL: "postgresql://postgres:postgresPassword@localhost:5432/eas-index"
    depends_on:
      - eas-postgres
    ports:
      - "4000:4000"

volumes:
  postgres_data:
